### ISSUE TITLE
Is there support for multiple languages on the Kwnowladgebase?

### ISSUE THREAD

**Issue by pepjo** [scott/helpy#18]
Is there support for multiple languages on the Kwnowladgebase?

**Comment by scott** [comment]
Hey thanks for the language contribution!  In the current master branch there is not (yet) but I have been working hard at adding that and expect to have it released to master very soon.

**Comment by pepjo** [comment]
That's fantastic! 😊 

Thanks for your great work!

**Comment by scott** [comment]
I don't know if you noticed, but I merged my dev branch into master a couple days ago and now the multi-lingual support is there!  I recommend updating to get this functionality.  Some documentation exists on 
http://support.helpy.io/knowledgebase/12-Using-Helpy/docs/9-How-to-set-up-a-mutlilingual-Helpy-support-knowledgebase

**Comment by pepjo** [comment]
That's amazing! That makes helpy the ultimate help desk for me!

I'll contribute Spanish translation as soon as I can.

**Comment by scott** [comment]
Awesome!  That would be very helpful :)  Let me know how it goes with the multilingual stuff- if you think of any improvements, find bugs, etc.

**Comment by pepjo** [comment]
Hi!
I have sent the pull request with spanish and some catalan improvements.

I have a doubt about upgrading though. On the wiki says that I must run: 
````
bundle install
RAILS_ENV=production rake assets:precompile
RAILS_ENV=production rake db:migrate
service nginx reload && service unicorn restart
````
However, since my helpy is deployed on heroku I am guessing that I only have to run the following command:
````
heroku run rake db:migrate
````
is this correct?

**Comment by scott** [comment]
That sounds correct to me.  I should probably enhance that article to cover both Ubuntu/Digital Ocean and Heroku!  Thanks for your translations :)

**Comment by pepjo** [comment]
(I don't know If I should keep posting to this thread since this is no longer related to the title :/ )

After updating the version on heroku and running the db:migrate command I got the following error:

````
Running rake db:migrate on kibus-help... up, run.1475
  ActiveRecord::SchemaMigration Load (4.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Migrating to TranslateDocs (20151027034830)
   (2.8ms)  BEGIN
== 20151027034830 TranslateDocs: migrating ====================================
   (37.5ms)  CREATE TABLE "doc_translations" ("id" serial primary key, "doc_id" integer NOT NULL, "locale" character var
ying NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
   (1.0ms)  ALTER TABLE "doc_translations" ADD "title" character varying
   (1.0ms)  ALTER TABLE "doc_translations" ADD "body" text
   (0.9ms)  ALTER TABLE "doc_translations" ADD "keywords" character varying
   (0.8ms)  ALTER TABLE "doc_translations" ADD "title_tag" character varying
   (2.1ms)  ALTER TABLE "doc_translations" ADD "meta_description" character varying
  Doc Load (5.1ms)  SELECT  "docs".* FROM "docs"  ORDER BY "docs"."id" ASC LIMIT 1000
  Doc::Translation Load (0.8ms)  SELECT "doc_translations".* FROM "doc_translations" WHERE "doc_translations"."doc_id" =
 $1  [["doc_id", 1]]
  SQL (1.0ms)  INSERT INTO "doc_translations" ("locale", "doc_id", "title", "body", "keywords", "title_tag", "meta_descr
iption", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"  [["locale", "en"], ["do
c_id", 1], ["title", "Accepted payment methods"], ["body", "<div>At the moment only credit cards are accepted</div>"], [
"keywords", "payment, methods, billing, card"], ["title_tag", "payment methods"], ["meta_description", ""], ["created_at
", "2015-11-28 12:35:24.075805"], ["updated_at", "2015-11-28 12:35:24.075805"]]
   (9.6ms)  ROLLBACK
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `locale=' for #<PaperTrail::Version:0x007f34f9d82388>/app/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2
.0/lib/active_model/attribute_methods.rb:433:in `method_missing'
/app/vendor/bundle/ruby/2.2.0/gems/globalize-versioning-0.1.0/lib/globalize/versioning/paper_trail.rb:31:in `block (2 le
vels) in <top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:443:in `instance_exec'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:443:in `block in make_lambda'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in `block in halting'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
````

plus a thousand more lines....

And when I try to go to the app I get:
````
We're sorry, but something went wrong.

If you are the application owner check the logs for more information.
````

I'll probably do a clean install anyway but I wanted to let you know.

**Comment by scott** [comment]
I still have not had a chance to try and replicate this, but did you run `bundle install` on your local before you pushed to remote on heroku?  It could also be that the `add_locale_to_versions` did not run.

**Comment by scott** [comment]
I finally figured out what causes this issue and how to fix it.  Basically the migrations are in the wrong order- I will release a fix for this but in the meantime you can manually run the migration which adds the locale column to the versions database first, then run db:migrate like normal second and everything should work:

`RAILS_ENV=production rake db:migrate:up VERSION=20151107185413`

and then

RAILS_ENV=production rake db:migrate`

**Comment by pepjo** [comment]
Hi!,

I finally had time to update. I works wonderfully! Thanks for your hard work :smile:

**Comment by scott** [comment]
Thanks!  Let me know what other suggestions you have!
