### ISSUE TITLE
create tickets from custom email without the need of an third party provider like mandrill

### ISSUE THREAD

**Issue by zefanja** [scott/helpy#23]
First of all: I like to progress and look and feel of helpy a lot! Great project!

It would be nice if you can configure a custom support email and tickets than are created automatically without the need of an external / third party provider.

This would be easier to setup (as a user) and it is also better for data sensitive environments where the use of third party tools is not permitted.

**Comment by scott** [comment]
I have been looking at something like Mailin.io for this.  This is an open source project that does the same thing as the external providers.  Check out https://github.com/Flolagale/mailin  There is also a mailin adaptor for griddler, which Helpy uses to help parse the messages.

I just noticed Mandrill no longer appears to offer 12000 emails a month for free.  Will have to stop recommending them :)

**Comment by zefanja** [comment]
Thank you! I'll check that out.
