### ISSUE TITLE
API

### ISSUE THREAD

**Issue by joshmn** [scott/helpy#28]
Hey Scott,

I like what you're doing here and I'd like to help, if you'd like to have me. :)

Do you have any strong feelings towards using Grape[0] for the API? 

Some other things I think would be roadmappable... jwt, multiple companies, assigning a group to a user — and having a group permission for forums/kb/tickets. I can talk more about them later (have a meeting to run to here shortly) but just putting it out there. 

I was going to create and opensource my own helpdesk solution until I stumbled upon this badboy. My stack was going to be similar, except I would have used activeadmin to crank out the admin back-end stuff. 

[0] https://github.com/ruby-grape/grape

Cheers,

**Comment by scott** [comment]
Hi Josh!

Thanks for your interest and for your votes of confidence too!  I would love to have you help out, and grape looks like an awesome option for an api.  I'd love to learn more about your ideas for other functionality too.  Let me know if you need anything from me or want to bounce ideas back and forth!  You can ping me at scott.miller.utah-at-gmail-com

Scott

**Comment by joshmn** [comment]
Sounds great! I'm excited! Grape is awesome and (honestly) a lifesaver. I
prefer its dsl (very... sinatra-like) versus blowing up actioncontroller.

I shot you an email as a bcc to this reply — you can poke me when you want
to, too. :) josh@josh.theabbreviationforminnesota

I'll pull 'er down and see what I can get done. Cool stuff to follow.

I love helpdesks.

On Mon, Dec 7, 2015 at 9:22 PM, Scott Miller <notifications@github.com>
wrote:

> Hi Josh!
>
> Thanks for your interest and for your votes of confidence too! I would
> love to have you help out, and grape looks like an awesome option for an
> api. I'd love to learn more about your ideas for other functionality too.
> Let me know if you need anything from me or want to bounce ideas back and
> forth! You can ping me at scott.miller.utah-at-gmail-com
>
> Scott
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scott/helpy/issues/28#issuecomment-162747602>.
>



-- 

Hello from Minneapolis  Josh Brody   (952) 239-7408  www
<http://www.josh.mn>

**Comment by scott** [comment]
Got your email too.  Excited to see what you do!
