### ISSUE TITLE
Error: Dangerous Send

### ISSUE THREAD

**Issue by ecopes** [scott/helpy#6]
Error: Dangerous Send
In strategy.rb in OmniAuth before 1.3.2, the authenticity_token value is improperly protected because POST (in addition to GET) parameters are stored in the session and become available in the environment of the callback phase.

Category description: Using unfiltered user data to select a Class or Method to be dynamically sent is dangerous.
Solution: upgrade omniauth to >= 1.3.2

**Comment by scott** [comment]
Hi @ecopes thanks for contributing these issues! The issues may have been fixed in the master branch- can you please take a look at https://github.com/helpyio/helpy and see if you see the same issue there and if so, re-post there.
