### ISSUE TITLE
use titleize only in english

### ISSUE THREAD

**Issue by pepjo** [scott/helpy#60]
Hi again,

I just want a let you know that the title case is only used in english (at least, it is not used in spanish or catalan) and looks horrible on other languages. I'm saying that because Helpy does `.titleize` every title without taking into consideration the locale.

I've removed every `.titleize` in my helpy fork and manually type the english titles in title case, but I realise this is not the correct way :/

**Comment by scott** [comment]
@pepjo Thanks!  I did not know this.  So are you referring to the titles of articles and categories specifically, or pretty much everywhere?  Do you suggest we leave it up the locale.yml to determine correct titleization for navigation, system messages, etc?

**Comment by pepjo** [comment]
Pretty much everywhere, but looks worse on longer sentences like titles and categories.

Yes, I feel that that would be the proper way to do it.

**Comment by olliebennett** [comment]
I agree it's probably overkill to `.titleize` everything when displaying it.

Perhaps converting to **sentence case** could still be appropriate for post titles etc. It seems there must be _some_ rules common to most languages, and sentence case is hopefully more acceptable than `titleize`. Would that work?

I think regardless of our decision, it should be possible to edit the string into any desired format. The solution we use (specifically with user's names) is to have a `titleize_lowercased_names` `before_create` hook, in which we effectively `titleize` the name only if it's all lowercase. This means people lazily entering `ollie bennett` will have their name converted to `Ollie Bennett` (which looks better), but users entering `Ollie de XXX` won't (incorrectly) become `Ollie Van Xxx`, for example, and if we incorrectly assume the capitalisation rules, they can override any assumptions by editing after creation.

**Comment by scott** [comment]
@pepjo So you are saying @olliebennetts suggestion (and mine too) of doing first word capitalization will work?  Thats just `@doc.title.capitalize` instead of `titleize`.  So is the titleize likely messing up the German pretty bad?  I don't know much about German.

**Comment by pepjo** [comment]
@olliebennett yes, as far as I know sentence case is fine for most languages! I didn't know about the username capitalitzation system, looks pretty bad ass to me :smile: 

@scott Yes, I think so. About German, its definitly readable its just harder and looks bad beacouse people are not used to it.

**Comment by scott** [comment]
@pepjo I have one more question for you- for things like "Category Name"  such as "Common Questions" in English we would typically titleize this.  What is the normal practice for Spanish, German, etc?

**Comment by pepjo** [comment]
We never titleize, under any circumstance. All the same, short sentences
like those don't feel as bad as longer sentences.

El dc, 2 març 2016 a les 18:37 Scott Miller <notifications@github.com> va
escriure:
