### ISSUE TITLE
Cannot post from Q&A and Matrix forums

### ISSUE THREAD

**Issue by scott** [scott/helpy#73]
Not sure when this was introduced, but even when logged in, I cannot post messages from these views.

**Comment by olliebennett** [comment]
Hey @scott - not quite sure how to reproduce this. What are the "Matrix" forums? Keen to fix it I can reproduce it.

**Comment by scott** [comment]
Yeah I am not sure, when I went back to try on my end I was having troubles reproducing it as well.  Let me dig into it a bit more and see if I can figure it out.

**Comment by olliebennett** [comment]
Sweet. If you have a screenshot of what exactly you mean by these pages anyway, it'd be good to understand the terminology you're using for the project.

**Comment by scott** [comment]
When you create or edit a forum there is a selection for the format.  Table based is what most forums look like.  There are two others- Q&A which is kinda like Quora, and Grid (what I called matrix by accident.) which is a poorly conceived version of what a card base layout might look like.

On all of the forums, if you are not logged in, there should be a button to "Reply" or something- which will prompt a login if you are not logged in, or open the post message dialogue if you are.  What I saw on my localhost was that I was logged in, and still being prompted to login when I clicked these.  However, later on I tried it again and everything seemed okay.... so I am not sure what it is and left this issue more as a reminder to myself to dig into it further.  It also spurred me to write some decent integration tests of key functionality :)

**Comment by olliebennett** [comment]
Okay - got it, thanks! Makes much more sense now; cheers for the detailed info. Will leave you to it to try and reproduce, although my first guess would be it's related to a session timeout so might be worth logging out in another tab to see if that triggers it.

**Comment by scott** [comment]
Alright I figure out what I was talking about above, and am working on a fix now :)
