### ISSUE TITLE
How to add support users?

### ISSUE THREAD

**Issue by michaelgobbers** [scott/helpy#8]
Hi,

I've setup a helpy installation on heroku. I've been able to login with the default admin user and change it to my own user. However, I'm not able to add more users to the support team. How should I do this?

Cheers,
Michael

**Comment by scott** [comment]
Hi Michael,

Ironic.  I was thinking last night how I need to add an article on how to add support users, or make it more obvious in the admin panel!  Here is what you should do:

1. Have each of the support team/users go to Helpy and open a private ticket requesting to be added.  This also creates their user account on Helpy.
2. From the admin panel, click on the name (not ticket) of each user.  This will open a page that shows the user details and discussion history.
3. There is a link next to the user name to 'edit' them.  Click this.
4. Scroll down and you will see two checkboxes, one for 'active' and one for 'admin'.  Check admin, and save the user.
5. That individual should now be able to sign in as an agent.
